name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install --system -r requirements.txt
      - name: Install linters
        run: |
          uv pip install --system ruff black isort
      - name: Run ruff with auto-fix
        run: ruff check . --fix
      - name: Run isort with auto-fix
        run: isort .
      - name: Run black with auto-fix
        run: black .
      - name: Commit lint fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format code with ruff, black, isort [auto]"
          branch: ${{ github.head_ref }}
      - name: Check ruff (fail if 문제 남음)
        run: ruff check .
      - name: Check black (fail if 문제 남음)
        run: black --check .
      - name: Check isort (fail if 문제 남음)
        run: isort --check .
