
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install --system -r requirements.txt
      - name: Install ruff
        run: uv pip install --system ruff
      - name: Run ruff
        run: ruff check . --fix ; echo "Ruff check completed"
      - name: Install black
        run: uv pip install --system black
      - name: Run black
        run: black --check . ; echo "Black check completed"
      - name: Install isort
        run: uv pip install --system isort
      - name: Run isort
        run: isort --check . ; echo "isort check completed"
